spring.application.name=enjambre

# ========== SERVIDOR ==========
server.port=${PORT:8080}

# ========== BASE DE DATOS ==========
spring.jpa.database=mysql
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ⚠️ CORREGIDO: Agrega "jdbc:" al inicio y cambia el primer "mysql:" por "jdbc:mysql:"
spring.datasource.url=jdbc:${MYSQL_URL}
spring.datasource.username=${MYSQL_USER:root}
spring.datasource.password=${MYSQL_ROOT_PASSWORD:12345678}

# ========== CORREO ==========
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=countercito10@gmail.com
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ========== THYMELEAF ==========
spring.thymeleaf.cache=false

# ========== MULTIPART (CARGA DE ARCHIVOS) ==========
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB

